AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Authentication Snackhub Project

Globals:
  Function:
    Timeout: 20
    MemorySize: 512

Resources:
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build/distributions/lambda-authentication-1.0-SNAPSHOT.zip
      Handler: com.snackhub.handler.AuthLambda::handleRequest
      Runtime: java17
      Architectures:
        - x86_64
      MemorySize: 512
      Environment:
        Variables:
          PARAM1: VALUE
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccessF
        - AWSLambdaVPCAccessExecutionRole
      Tracing: Active
