name: Build Project with Gradle and Deploy AWS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Make gradlew executable
      run: chmod +x ./gradlew
      
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3
    
    - name: Build with Gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        arguments: build

    - name: Archive build artifacts
      run: |
        mkdir -p build-artifacts
        cp build/distributions/lambda-authentication*.zip build-artifacts/
      working-directory: ${{ github.workspace }}

    - name: Upload ZIP artifact
      uses: actions/upload-artifact@v2
      with:
        name: lambda-authentication.zip
        path: build-artifacts/lambda-authentication*.zip

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Create AWS Lambda Function
      run: |
        aws lambda create-function --function-name lambda-authentication --runtime java17 --handler com.snackhub.handler.AuthLambda::handleRequest --zip-file $GITHUB_WORKSPACE/build-artifacts/my-project-artifact.zip
      continue-on-error: true  
    - name: Update Lambda Function    
      run: aws lambda update-function-code --function-name lambda-authentication --zip-file $GITHUB_WORKSPACE/build-artifacts/my-project-artifact.zip

